"""Add sequence to vote_seq

Revision ID: 28592c1b9caa
Revises: 4eb957e54930
Create Date: 2026-08-23 11:56:10.142341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28592c1b9caa'
down_revision: Union[str, Sequence[str], None] = '4eb957e54930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sqg_users_userid'), table_name='sqg_users')
    op.drop_table('sqg_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqg_users',
    sa.Column('userid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_dt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userid', name=op.f('sqg_users_pkey'))
    )
    op.create_index(op.f('ix_sqg_users_userid'), 'sqg_users', ['userid'], unique=False)
    # ### end Alembic commands ###
