"""create init tables

Revision ID: 40ba486392fa
Revises: 815b80a074e6
Create Date: 2026-08-18 23:24:33.200333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ba486392fa'
down_revision: Union[str, Sequence[str], None] = '815b80a074e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_b', sa.Column('auth_cd', sa.String(length=10), nullable=True, comment='권한코드 (01:관리자, 02:일반)'))
    op.add_column('user_h', sa.Column('auth_cd', sa.String(length=10), nullable=True, comment='권한코드 (01:관리자, 02:일반)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_h', 'auth_cd')
    op.drop_column('user_b', 'auth_cd')
    # ### end Alembic commands ###
