"""create init tables

Revision ID: 815b80a074e6
Revises: e3af9d808c83
Create Date: 2026-08-18 23:20:08.220707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815b80a074e6'
down_revision: Union[str, Sequence[str], None] = 'e3af9d808c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_cd_b',
    sa.Column('group_cd', sa.String(length=20), nullable=False, comment='그룹코드'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='코드'),
    sa.Column('code_name', sa.String(length=100), nullable=True, comment='코드명'),
    sa.Column('code_seq', sa.Integer(), nullable=True, comment='코드순서'),
    sa.Column('reference_1', sa.String(length=255), nullable=True, comment='참조1'),
    sa.Column('reference_2', sa.String(length=255), nullable=True, comment='참조2'),
    sa.Column('reference_3', sa.String(length=255), nullable=True, comment='참조3'),
    sa.Column('reference_4', sa.String(length=255), nullable=True, comment='참조4'),
    sa.Column('use_yn', sa.String(length=1), nullable=True, comment='사용유무'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('group_cd', 'code'),
    comment='공통코드'
    )
    op.create_table('common_group_cd_b',
    sa.Column('group_cd', sa.String(length=20), nullable=False, comment='그룹코드'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='그룹코드명'),
    sa.Column('use_yn', sa.String(length=1), nullable=True, comment='사용유무'),
    sa.Column('start_date', sa.String(length=8), nullable=True, comment='적용시작일자'),
    sa.Column('end_date', sa.String(length=8), nullable=True, comment='적용종료일자'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('group_cd'),
    comment='공통코드그룹'
    )
    op.create_table('team_account_l',
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('team_account_seq', sa.Integer(), autoincrement=True, nullable=False, comment='시퀀스'),
    sa.Column('bank_cd', sa.String(length=20), nullable=False, comment='은행코드'),
    sa.Column('account_enc', sa.String(length=255), nullable=False, comment='계좌번호'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('team_uid', 'team_account_seq', 'bank_cd', 'account_enc'),
    comment='팀 계좌 리스트'
    )
    op.create_table('team_arrange_l',
    sa.Column('vote_uid', sa.String(length=50), nullable=False, comment='투표아이디'),
    sa.Column('play_date', sa.String(length=8), nullable=True, comment='경기일자'),
    sa.Column('team_cd', sa.String(length=20), nullable=True, comment='팀구분코드'),
    sa.Column('member_id', sa.String(length=50), nullable=True, comment='멤버아이디'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('vote_uid'),
    comment='팀 배정 리스트'
    )
    op.create_table('team_info_b',
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('teamname', sa.String(length=100), nullable=True, comment='팀명'),
    sa.Column('region_cd', sa.String(length=20), nullable=True, comment='지역'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='위치'),
    sa.Column('start_time', sa.String(length=10), nullable=True, comment='활동시간FR'),
    sa.Column('end_time', sa.String(length=10), nullable=True, comment='활동시간TO'),
    sa.Column('day_cd', sa.String(length=20), nullable=True, comment='활동요일'),
    sa.Column('level_cd', sa.String(length=10), nullable=True, comment='실력 (01: S, 02: A, 03: B, 04: C, 05: D, 06: F)'),
    sa.Column('gender_cd', sa.String(length=10), nullable=True, comment='성별 (01:남자, 02: 여자, 03: 혼성)'),
    sa.Column('use_yn', sa.String(length=1), nullable=True, comment='사용여부'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='코멘트'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('team_uid'),
    comment='팀정보 기본'
    )
    op.create_table('team_member_l',
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('member_uid', sa.String(length=50), nullable=False, comment='멤버아이디'),
    sa.Column('member_name', sa.String(length=50), nullable=True, comment='멤버이름'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='유저아이디'),
    sa.Column('sign_dt', sa.String(length=14), nullable=True, comment='가입일자'),
    sa.Column('gender_cd', sa.String(length=10), nullable=True, comment='성별 (01:남자, 02: 여자)'),
    sa.Column('status_cd', sa.String(length=10), nullable=True, comment='상태 (01: 활동, 02: 부상, 03: 휴식)'),
    sa.Column('terminate_dt', sa.String(length=14), nullable=True, comment='탈퇴일자'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.PrimaryKeyConstraint('team_uid', 'member_uid'),
    comment='팀 멤버 리스트'
    )
    op.create_table('team_member_score_l',
    sa.Column('member_uid', sa.String(length=50), nullable=False, comment='멤버아이디'),
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('year', sa.String(length=4), nullable=False, comment='년도'),
    sa.Column('score_cd', sa.String(length=20), nullable=False, comment='점수코드 (시트 2 참조)'),
    sa.Column('score_val', sa.Numeric(), nullable=True, comment='점수'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('member_uid', 'team_uid', 'year', 'score_cd'),
    comment='팀 점수 리스트'
    )
    op.create_table('team_payment_l',
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('payment_cd', sa.String(length=20), nullable=False, comment='비용용도'),
    sa.Column('team_account_seq', sa.Integer(), nullable=False, comment='시퀀스'),
    sa.Column('amount', sa.Numeric(), nullable=True, comment='비용'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('team_uid', 'payment_cd', 'team_account_seq'),
    comment='팀 비용 리스트'
    )
    op.create_table('team_record_l',
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('vote_uid', sa.String(length=50), nullable=False, comment='투표아이디'),
    sa.Column('play_date', sa.String(length=8), nullable=False, comment='경기일자'),
    sa.Column('member_uid', sa.String(length=50), nullable=True, comment='멤버아이디'),
    sa.Column('goal_cnt', sa.Integer(), nullable=True, comment='골 수'),
    sa.Column('asist_cnt', sa.Integer(), nullable=True, comment='도움 수'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('team_uid', 'vote_uid', 'play_date'),
    comment='팀 기록실 리스트'
    )
    op.create_table('team_schedule_l',
    sa.Column('vote_seq', sa.Integer(), autoincrement=True, nullable=False, comment='투표아이디'),
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('play_date', sa.String(length=8), nullable=True, comment='경기일자'),
    sa.Column('play_start_time', sa.String(length=10), nullable=True, comment='경기시작시간'),
    sa.Column('play_end_time', sa.String(length=10), nullable=True, comment='경기종료시간'),
    sa.Column('vote_period_from', sa.String(length=14), nullable=True, comment='투표기간from'),
    sa.Column('vote_period_to', sa.String(length=14), nullable=True, comment='투표기간to'),
    sa.Column('vote_end_yn', sa.String(length=1), nullable=True, comment='투표종료여부'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('vote_seq', 'team_uid'),
    comment='팀 일정 리스트'
    )
    op.create_table('team_startdium_l',
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('team_stardium_seq', sa.Integer(), autoincrement=True, nullable=False, comment='시퀀스'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='위치'),
    sa.Column('start_time', sa.String(length=10), nullable=True, comment='활동시간FR'),
    sa.Column('end_time', sa.String(length=10), nullable=True, comment='활동시간TO'),
    sa.Column('day_cd', sa.String(length=20), nullable=True, comment='활동요일'),
    sa.Column('main_locate_yn', sa.String(length=1), nullable=True, comment='주구장여부'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('team_uid', 'team_stardium_seq'),
    comment='팀 구장 리스트'
    )
    op.create_table('team_vote_l',
    sa.Column('vote_seq', sa.Integer(), nullable=False, comment='투표아이디'),
    sa.Column('team_uid', sa.String(length=50), nullable=False, comment='팀아이디'),
    sa.Column('play_date', sa.String(length=8), nullable=True, comment='경기일자'),
    sa.Column('play_start_time', sa.String(length=10), nullable=True, comment='경기시작시간'),
    sa.Column('play_end_time', sa.String(length=10), nullable=True, comment='경기종료시간'),
    sa.Column('member_uid', sa.String(length=50), nullable=True, comment='멤버아이디'),
    sa.Column('vote_cd', sa.String(length=20), nullable=True, comment='투표코드'),
    sa.Column('create_id', sa.String(length=50), nullable=True, comment='등록자'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록시간'),
    sa.Column('update_id', sa.String(length=50), nullable=True, comment='수정자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정시간'),
    sa.PrimaryKeyConstraint('vote_seq', 'team_uid'),
    comment='팀 투표 리스트'
    )
    op.create_table('user_b',
    sa.Column('userid', sa.String(length=50), nullable=False, comment='아이디'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='이름'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('last_login_dt', sa.DateTime(), nullable=True, comment='최종접속일자'),
    sa.Column('use_yn', sa.String(length=1), nullable=True, comment='사용여부 (Y/N)'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='닉네임'),
    sa.Column('kakao_name', sa.String(length=100), nullable=True, comment='카카오닉네임'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록일자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정일자'),
    sa.PrimaryKeyConstraint('userid'),
    comment='유저정보 기본'
    )
    op.create_table('user_h',
    sa.Column('userid', sa.String(length=50), nullable=False, comment='아이디'),
    sa.Column('user_seq', sa.Numeric(), nullable=False, comment='시퀀스'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='이름'),
    sa.Column('use_yn', sa.String(length=1), nullable=True, comment='사용여부'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='닉네임'),
    sa.Column('kakao_name', sa.String(length=100), nullable=True, comment='카카오닉네임'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('create_dt', sa.DateTime(), nullable=True, comment='등록일자'),
    sa.Column('update_dt', sa.DateTime(), nullable=True, comment='수정일자'),
    sa.PrimaryKeyConstraint('userid', 'user_seq'),
    comment='유저정보 이력'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_h')
    op.drop_table('user_b')
    op.drop_table('team_vote_l')
    op.drop_table('team_startdium_l')
    op.drop_table('team_schedule_l')
    op.drop_table('team_record_l')
    op.drop_table('team_payment_l')
    op.drop_table('team_member_score_l')
    op.drop_table('team_member_l')
    op.drop_table('team_info_b')
    op.drop_table('team_arrange_l')
    op.drop_table('team_account_l')
    op.drop_table('common_group_cd_b')
    op.drop_table('common_cd_b')
    # ### end Alembic commands ###
