"""초기 테이블 뼈대 세팅

Revision ID: e3af9d808c83
Revises: 
Create Date: 2026-08-10 18:52:19.634094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3af9d808c83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sqg_users_userid'), 'sqg_users', ['userid'], unique=False)
    op.drop_column('sqg_users', 'login_dt')
    op.drop_column('sqg_users', 'is_active')
    op.drop_column('sqg_users', 'change_password_dt')
    op.drop_column('sqg_users', 'pre_password')
    op.drop_column('sqg_users', 'updated_dt')
    op.drop_column('sqg_users', 'login_try_cnt')
    op.drop_column('sqg_users', 'is_locked')
    op.drop_column('sqg_users', 'ip')
    op.drop_column('sqg_users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sqg_users', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('ip', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('is_locked', sa.VARCHAR(length=1), server_default=sa.text("'N'::character varying"), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('login_try_cnt', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('updated_dt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('pre_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('change_password_dt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('is_active', sa.VARCHAR(length=1), server_default=sa.text("'Y'::character varying"), autoincrement=False, nullable=True))
    op.add_column('sqg_users', sa.Column('login_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sqg_users_userid'), table_name='sqg_users')
    # ### end Alembic commands ###
